### ISSUE TITLE
Getting server to serve static index.html

### ISSUE THREAD

**Issue by cattius** [ofaucoz/trackr#5]
This is probably me being an idiot but even after adding a file handler to standalone.xml I still can't get the server to serve index.html (at http://localhost:8080/trackr/index.html or at http://localhost:8080/trackr/) with relative or absolute file paths - it says it sets up a file handler for the right file address and everything looks ok with no errors, but then when I try and access the address it just tells me Not Found.

**Comment by ofaucoz** [comment]
You put all the static contents in the frontend directory, where it should be in the WebContent directory, once you transfer everything from the frontend directory to the WebContent directory it'll work(as in the second picture)
![image](https://user-images.githubusercontent.com/19463766/34339511-5861ab5c-e975-11e7-8444-d83c3dbe8ab1.png)
![image](https://user-images.githubusercontent.com/19463766/34339491-1e6ba65a-e975-11e7-9623-b5f4d6f384e3.png)

**Comment by ofaucoz** [comment]
By the way, the frontend directory is a mess, @asstg can you change the AndreasCode.html to something meaningful, and why is there a package inside the directory? that's not how it should be, we have 4K lines of codes that souldn't appear on the commits.

**Comment by cattius** [comment]
Awesome, thanks. Fixed on master branch - also tidied up the frontend directory.
